### ISSUE TITLE
RangeError buffer on encrypt function call

### ISSUE THREAD

**Issue by ghost** [simplito/xtea-js#1]
`var xtea = require('xtea');

	var str = Buffer.from('encoder', 'utf8');
	var key = Buffer.from('666f6f626172', 'hex');
	var ciphertext = xtea.encrypt(str, key);
	console.log(ciphertext.toString('hex'));`

i get this error buffer.js:839
    throw new RangeError('Index out of range');
    ^

RangeError: Index out of range
    at checkOffset (buffer.js:839:11)
    at Buffer.readUInt32BE (buffer.js:913:5)

on encrypt function call
could you help me please ?

**Comment by ghost** [comment]
my bad

**Comment by ssmyczynski** [comment]
The `key` size for XTEA is fixed to 16 bytes and your key has only 6 bytes.
Your example works well if you change the line with the key:
```
var xtea = require('xtea');
var str = Buffer.from('encoder', 'utf8');
var key = Buffer.from('666f6f62617200000000000000000000', 'hex');
var ciphertext = xtea.encrypt(str, key);
console.log(ciphertext.toString('hex'));`
```
